config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only:[:show, :edit, :update, :destroy ]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :description)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>What the cut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('mylogo.png'), :rel => 'icon', :type =>  'image/png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8">
      <div class="card-form">
        <h2 class="mb-5">Your new list</h2>
        <%= simple_form_for(@list) do |f|%>
          <%= f.input :name, placeholder: "My list#12" %>
          <%= f.input :description, placeholder: "How would you best describe your list?" %>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="container">
  <% if List.all.empty? %>
    <h2>You don't have a list yet !</h2>
    <%= link_to "Create your first list", new_list_path %>
  <% else %>
    <% @lists.each do |list|%>
      <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
          <%= link_to list_path(list), class: "list-link" do %>
            <ul class="p-3">
              <li><h3><%= list.name %></h3></li>
              <li><p><%= list.description %></p></li>
              <li><span>x movies</span></li>
            </ul>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="container">
  <ul class="list-inline">
    <li class="list-inline-item">
      <h2><%= @list.name %></h2>
    </li>
    <li class="list-inline-item">
      <%= link_to edit_list_path(@list) do %>
        <i class="far fa-edit"></i>
      <% end %>
    </li>
    <li class="list-inline-item">
      <%= link_to list_path(@list), method: :delete, data: {confirm: "are you sure?"} do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </li>
  </ul>
  <p class="mt-4 mb-0"><%= @list.description %></p>
  <p style="opacity: .7">Created by username - x movies </p>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-12 col-lg-6 mb-2">
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2><%= Movie.first.title %>Movie title - Year</h2>
          <p><i class="far fa-clock"></i> Runtime - Genre</p>
          <p>Work by Director</p>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2>Movie title - Year</h2>
          <p><i class="far fa-clock"></i> Runtime - Genre</p>
          <p>Work by Director</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-12 col-lg-6 mb-2">
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2>Movie title - Year</h2>
          <p><i class="far fa-clock"></i> Runtime - Genre</p>
          <p>Work by Director</p>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2>Movie title - Year</h2>
          <p><i class="far fa-clock"></i> Runtime - Genre</p>
          <p>Work by Director</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner.jpg" %>');">
  <div class="container">
    <h1>What the cut</h1>
    <p>Discover something great to watch</p>
    <form id="search-movies">
      <div class="form-row align-items-center">
        <div class="col-auto">
          <input type="text" class="form-control mb-2" id="keyword" placeholder="Find movies">
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-primary mb-2">Search</button>
        </div>
      </div>
    </form>
  </div>
</div>


<div class="container m-5" style="max-width: 1400px;">
  <div id="results" class="cards">
  </div>
</div>


<div class="container">
  <div class="text-right">
    <div class="btn-group d-none">
      <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Add to list
      </button>
      <div class="dropdown-menu">
        <% List.all.each do |list|%>
          <%= simple_form_for list do |f|%>
            <%= f.input :name, as: :hidden, input_html: { value: "#{list.description}" } %>
            <%= f.input :description, as: :hidden, input_html: { value: "#{list.description}" } %>
            <%= f.button :submit, "#{list.name}", class: "dropdown-item list-name" %>
          <% end %>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "New list", new_list_path, class: "dropdown-item" %>
      </div>
    </div>
  </div>
  <div id="movie">

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="footer-card">
        <div class="footer-links">
          <a href="https://www.linkedin.com/in/matthieu-hedin/" class="fab fa-linkedin" target="_blank"></a>
          <a href="https://github.com/MrBloon" class="fab fa-github" target="_blank"></a>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="footer-card">
        <p>Made with <i class="fas fa-heart"></i> by MrBloon</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "mylogo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My lists", lists_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>